### ISSUE TITLE
Stage 2 rack servers fails

### ISSUE THREAD

**Issue by vallard** [CiscoUcs/KUBaM#2]
Running stage2 python script gets the error: 

```
# ./kubeucs.py -o micdoher1425 admin nbv12345 172.28.225.163
Checking if org micdoher1425 exists
Org micdoher1425 does not exist
Creating Organization: micdoher1425
[1] VLAN default
[2] VLAN hx-inband-mgmt
[3] VLAN hx-vmotion
[4] VLAN hx-data
[5] VLAN Docker-Data
[6] VLAN Docker-storage
[7] VLAN hx-storage-data
[8] VLAN vm-network
--------------------------------------------------------------------------------
Please Select a VLAN for the Kubernetes Server to use: 1
Creating Kubernetes MAC Pools
org: org-root/org-micdoher1425
Creating Kubernetes VNIC Templates
Creating Kubernetes LAN connectivity policy
Creating Kube Boot Policy
Creating Kube Bios policy
Adding Disk Group Config
Creating Kube UUID Pools
Creating Kubernetes Compute Pool
Adding Virtual Media Policy
What is the URL for the Boot ISO image?
(E.g.: http://192.168.2.2/kubam/centos7.2-boot.iso) : http://172.28.225.60/kubam/centos7.3-boot.iso
You entered: http://172.28.225.60/kubam/centos7.3-boot.iso
Is this correct? [y/N]: y
Listing Available UCS Servers
[1]: Blade 1/slot-1 type UCSB-B200-M4
[2]: Blade 1/slot-3 type UCSB-B200-M3
[3]: Blade 1/slot-5 type UCSB-B200-M3
[4]: Blade 1/slot-6 type UCSB-B200-M3
[5]: Blade 1/slot-7 type UCSB-B200-M3
[6]: Blade 1/slot-8 type UCSB-B200-M3
[7]: Rack rack-unit-1 type HX240C-M4SX
[8]: Rack rack-unit-2 type HX240C-M4SX
[9]: Rack rack-unit-3 type HX240C-M4SX
[10]: Rack rack-unit-4 type HX240C-M4SX
[11]: Rack rack-unit-7 type UCSC-C220-M3S
[12]: Rack rack-unit-8 type UCSC-C220-M3S
[13]: Rack rack-unit-9 type UCSC-C220-M3S
[14]: Rack rack-unit-11 type UCSC-C240-M4SX
[15]: Rack rack-unit-12 type UCSC-C240-M4SX
[16]: Rack rack-unit-6 type UCSC-C220-M3S
[17]: Rack rack-unit-10 type UCSC-C240-M4SX
[18]: Rack rack-unit-5 type UCSC-C220-M3S
(E.g.: 2,4,8): 16,11,12
Install Kubernetes on the following servers:
            Server rack-unit-6 type UCSC-C220-M3S
            Server rack-unit-7 type UCSC-C220-M3S
            Server rack-unit-8 type UCSC-C220-M3S
Is this correct? [N/y]: y
Adding servers to Kubernetes Pool
Traceback (most recent call last):
  File "./kubeucs.py", line 59, in <module>
    main()
  File "./kubeucs.py", line 42, in main
    UCSServer.createKubeServers(handle, org)
  File "/root/Code/KUBaM/stage2/server/UCSServer.py", line 521, in createKubeServers
    addServersToKubePool(handle, servers, org)
  File "/root/Code/KUBaM/stage2/server/UCSServer.py", line 226, in addServersToKubePool
    reset_disks(handle, s)
  File "/root/Code/KUBaM/stage2/server/UCSServer.py", line 78, in reset_disks
    for d in disks:
TypeError: 'NoneType' object is not iterable
```

**Comment by vallard** [comment]
I think the issue here is with the rack mount servers as with the blades I try to delete the orphaned disks.  

Line 76:
```
from ucsmsdk.mometa.storage.StorageLocalDisk import StorageLocalDisk
    disks = list_disks(handle, server)
    for d in disks:
```
The rackmount servers don't get anything back for the list_disks call.  And you can tell from the function ```def list_disks``` on line 50 that in line 56 we simply didn't test the rackmount servers!  It even says: #don't do anything in the comments!  Yikes, dumb mistake.  I'll fix it.
